name: TestPlugin
version: '${project.version}'
main: me.hajder.testplugin.SumoPlugin
api-version: '1.20'
commands:
  sumo:
    description: "sumo"
    usage: "/sumo"
    aliases: [sumo, s]
    permission: sumo.admin
    permission-message: "No perms lil bro"